apiVersion: v1
kind: Service
metadata:
  name: {{ template "root-proxy.fullname" . }}
  labels:
    app: {{ template "root-proxy.name" . }}
    chart: {{ template "root-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: {{ template "root-proxy.name" . }}
    release: {{ .Release.Name }}
